name: swan_flutter_database
description: "A powerful and flexible Flutter package for seamless PHP & MySQL database integration, providing a robust connection between your Flutter application and PHP backend."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  image: ^4.5.2
  socket_io_client: ^3.0.2
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


